.github/workflows/maven.yml
Configures the default GitHub actions Maven workflow
=> Build and test project with GitHub actions

pom.xml, srv/pom.xml
Update CDS4J to 1.10.0
Remove cds-feature-mt workaround, as Maven Central dependency issues are finally resolved.
=> Update cds-services to 1.6.0

.npmrc
see https://jam4.sapjam.com/feed/item/eOtNGT1RSxVzknBtpSy2My for further details
=> remove @sap/registry config as all @sap modules are public available.

README.md
Further details: https://sapjira.wdf.sap.corp/browse/TECHCOREXS2-2158
=> Replace link to issues with link to answers

README.md, db/schema.cds, srv/src/test/java/my/bookshop/AdminServiceTest.java, srv/src/test/java/my/bookshop/CatalogServiceITest.java
Annotation `@assert.format` added to the field `name` of entity `Authors`  to assert that name starts with a capital letter
=> Showcase assertion annotations

.cdsrc.json, README.md, app/package.json, app/xs-app.json, cds-security-mt.json, cds-security.json, db/package.json, mta-multi-tenant.yaml, mta-single-tenant.yaml, mtx-sidecar/.cdsrc.json, mtx-sidecar/package.json, mtx-sidecar/server.js, pom.xml, srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java
- Configuration for single tenant deployment to SAP Cloud Platform
- Configuration for multi tenant deployment to SAP Cloud Platform
- Handlers for multi tenant subscription
=> Introduce SAP Cloud Platform deployment for single-tenancy and multi-tenancy (#25)

.gitignore, README.md, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java, srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java, srv/src/test/java/my/bookshop/handlers/CatalogServiceHandlerTest.java
I added some small improvements to the code and added a small docuementation snippet regarding IntelliJ usage.
=> some smaller improvements

pom.xml
- "_" are replaced with "-" by cf
=> Removed regex from maven-enforcer-plugin for artifactId

pom.xml, srv/src/main/resources/application.yaml, srv/src/test/java/my/bookshop/AdminServiceTest.java, srv/src/test/java/my/bookshop/CatalogServiceITest.java, srv/src/test/java/my/bookshop/handlers/CatalogServiceHandlerTest.java
Migrate to Spring Boot 2.4.1
Migrate to Junit 5
Set max-lifetime: 0 for in-memory SQLite as recommend here: https://cap.cloud.sap/docs/java/development/#sqlite
=> Update CDS Services to 1.13.0

srv/src/main/resources/application.yaml
with `spring.web.resources.static-locations` in application.yaml
- also see:
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/ResourceProperties.html#getStaticLocations--
=> Replace deprecated property `spring.resources.static-locations`

srv/cat-service.cds, srv/src/test/java/my/bookshop/AdminServiceTest.java, srv/src/test/java/my/bookshop/CatalogServiceITest.java, srv/src/test/java/my/bookshop/CatalogServiceTest.java
- Improved robustness by adding cleanup of reviews to relevant tests
- Simplified some code to showcase built-in functionality (e.g. toJson())
=> Improve tests

pom.xml, srv/src/main/java/my/bookshop/handlers/AdminServiceAddressHandler.java, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java, srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java, srv/src/main/java/my/bookshop/handlers/ReviewServiceHandler.java, srv/src/main/java/my/bookshop/handlers/external/ApiBusinessPartnerEventMockHandler.java, srv/src/main/resources/application.yaml, srv/src/test/java/my/bookshop/CatalogServiceTest.java
- Rename CdsService to CqnService
- Make use of projection support in RemoteServices
=> Update CDS Services to 1.15.0

mtx-sidecar/package.json
Update versions to ones specified in docs: https://cap.cloud.sap/docs/java/multitenancy#adding-the-mtx-sidecar-application
Support Node 14
=> Adapt mtx-sidecar package.json

pom.xml, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java, srv/src/main/java/my/bookshop/handlers/ReviewServiceHandler.java
CAP now automatically triggers throwIfError() at the end of the before phase
=> Update to CDS Services 1.18.0

pom.xml
Also updated cloud-sdk due to avoid inconsistencies with the xsuaa
versions.
=> Update cds-services to 1.19.0

pom.xml, srv/src/main/java/my/bookshop/config/DestinationConfiguration.java, srv/src/main/java/my/bookshop/handlers/AdminServiceAuditHandler.java, srv/src/main/resources/application.yaml
Showcase declarative destination configuration for API Hub destination
=> Update to CDS Services 1.20.0

db/books.cds, srv/src/main/java/my/bookshop/handlers/AdminServiceAuditHandler.java
- Annotate entity Author with personal data annotations
- audit log config changes for updates on orders.currency_code
=> Demo automatic personal data audit logs in Booshop sample

srv/src/main/java/my/bookshop/handlers/AdminServiceAuditHandler.java, srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java
This PR demonstrates how an audit log message can be send to the provider tenant.
=> send audit log message to provider tenant

mtx-sidecar/server.js, pom.xml
- Updated to cds-services version `1.24.0`
- Removed obsolete code from server.js
=> Updated dependency versions

app/addresses/webapp/index.html, app/admin/webapp/index.html, app/browse/webapp/index.html, app/notes/webapp/index.html, app/orders/webapp/index.html, app/reviews/webapp/index.html
This allows to test the UIs quickly with the central approuter (e.g. using Launchpad Service) without the need of any UI configuration.
=> Add single page index pages

db/books.cds
Replaced annotation value 'Create' with 'Insert'
=> Fixed issue in audit logging with missing insert messages.

scripts/create-db-secret.sh
Change binding structure to work with https://github.com/SAP/btp-environment-variable-access.
=> Create db service secret for new binding

mta-multi-tenant.yaml, mtx/sidecar/package.json
The configuration of build for MTX sidecar updated per recommendations for cds-dk 6.1+
=> Update of build configuration for MTX sidecar

xs-security-mt.json
As documented here: https://cap.cloud.sap/docs/java/multitenancy#xsuaa-mt-configuration
=> Add mtdeployment to authorities

app/package.json
`@sap/appruter:12.0.1` has some changes which make deploying `approuter` on Kyma very easy. 
It'd be great if this change is also merged with the `streamlined-mtx` branch.
=> update approuter version

app/appconfig/fioriSandboxConfig.json, app/fiori.html, app/orders/fiori-service.cds, app/xs-app.json
- Switched to Horizon theme
- Temporarily pins UI5 version to 1.110.1 due to issues.
- Fixed some quirks on the Orders UI
=> Switch to SAP Horizon theme

mtx/sidecar/package.json, srv/src/main/java/my/bookshop/config/WebSecurityConfig.java
Use new MTX Sidecar start command (see https://cap.cloud.sap/docs/releases/march23#change-your-start-script-to-cds-serve) Use @ConditionalOnWebApplication on security config to avoid initialization in MT commands
=> Minor optimizations

README.md
fixes: https://github.com/SAP-samples/cloud-cap-samples-java/issues/220
=> add missing instructions

mtx/sidecar/package.json, pom.xml
Fixes https://github.com/SAP-samples/cloud-cap-samples-java/issues/236
=> Update to @sap/cds-dk 7

.github/workflows/maven.yml, package.json
+ Adopt patch 1.3.1 for https://www.npmjs.com/package/@cap-js/postgres
+ Enable tests for this branch
=> Adopt cap js postgres 1.3.1

README.md
Related to https://github.com/SAP-samples/cloud-cap-samples-java/issues/259
=> Adjust steps for Single Tenant Kyma deployment

pom.xml, srv/pom.xml
Disable generation of localized EDMX.
=> Update @sap/cds-dk to 7.4.0

pom.xml
... of cds-services, and some 3rd party libs
=> Upgraded versions

srv/pom.xml
Removed deprecated XSUAA libraries.
=> Use cds-feature-identity

mta.yaml, pom.xml
PostgreSQL 14 is available in BTP: https://help.sap.com/docs/postgresql-hyperscaler-option/postgresql-on-sap-btp-hyperscaler-option-c92112ee69784c3383a0fb8361156a6f/2023-what-s-new-for-postgresql-hyperscaler-option-archive?locale=en-US
Parameters overview: https://help.sap.com/docs/postgresql-hyperscaler-option/postgresql-on-sap-btp-hyperscaler-option-c92112ee69784c3383a0fb8361156a6f/parameters?locale=en-US
=> Use cds-dk 7.7.1

integration-tests/pom.xml
Some build plugins in integration tests module are outdated.
=> Version bump build plugins

app/fiori.html, pom.xml
SAPUI5 versions: https://sapui5.hana.ondemand.com/versionoverview.html
=> Version bump of several dependencies

app/_i18n/i18n.properties, app/_i18n/i18n_de.properties
Closes https://github.com/SAP-samples/cloud-cap-samples-java/issues/310
=> Add i18n translation for Author labels

pom.xml
..and bump also other dependency versions
=> Update CDS Services to 2.8.2

pom.xml
Also fixes issues with Native Images and SAP Security Library
=> Update CAP Java to 2.9.1

app/fiori.html, app/orders/fiori-service.cds, integration-tests/pom.xml, mtx/sidecar/package.json, srv/admin-service.cds, srv/pom.xml
Adds change tracking for orders in the admin view.
Bumps Fiori version.
=> Add change tracking

.tours/sample-tour.tour
Closes https://github.com/SAP-samples/cloud-cap-samples-java/issues/332
=> Fix code tour and align with current content

pom.xml, srv/pom.xml, srv/src/main/resources/application.yaml
=> Use CAP Java 3.0

mtx/sidecar/package-lock.json, mtx/sidecar/package.json, pom.xml
Requires @sap/cds-dk devDependency to be independent of globally installed @sap/cds-dk
=> Fix mtx/sidecar build

app/_i18n/i18n.properties, app/_i18n/i18n_de.properties
Removes redundant entries from i18n files.
=> Remove duplicated items from i18n files

srv/review-service.cds
Reintroduced https://github.com/SAP-samples/cloud-cap-samples-java/pull/328 as issues with native images are resolved.
=> Use expression annotations in @restrict

README.md
Closes https://github.com/SAP-samples/cloud-cap-samples-java/issues/354
=> Improve IntelliJ setup instructions

.github/workflows/maven.yml
Currently used version (v1) doesn't support distribution `sapmachine`
=> Updated outdated actions/setup-java to v4

mta-multi-tenant.yaml, mta-single-tenant.yaml
We also must remove the extension in the internal bookshop test that changes the Java version.
=> Use Java 21 from buildpack

srv/src/main/java/my/bookshop/handlers/HierarchyHandler.java
Support of ExpandLevels in custom code
=> Support of ExpandLevels

pom.xml, srv/pom.xml
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#netty-in-native-image
=> Upgrade Spring Boot to 3.4.0

.github/workflows/maven.yml, mta.yaml, pom.xml
- Update JDK and SAPMachine in workflow to 21
- Update cds-dk to 8.6.1
- Update cds-services to 3.6.0
=> Update cds–services and cds-dk

srv/src/main/java/my/bookshop/config/DestinationConfiguration.java
https://github.wdf.sap.corp/cds-java/home/issues/1887
=> Refactor destination for mocked remote service

.cdsrc.json, app/addresses/webapp/manifest.json, app/admin/webapp/manifest.json, app/browse/webapp/manifest.json, app/genres/webapp/manifest.json, app/notes/webapp/manifest.json, app/orders/webapp/manifest.json, app/package-lock.json, app/reviews/webapp/manifest.json, db/package-lock.json, mtx/sidecar/package-lock.json, package-lock.json, pom.xml, srv/notes-mashup.cds, srv/src/main/java/my/bookshop/MessageKeys.java, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java, srv/src/main/resources/messages.properties, srv/src/main/resources/messages_de.properties
- Updates @sap/cds-dk to 8.8.0 and CDS Services to 3.8.0
- Enables Draft Messages
- Enables OData containment
=> Update CDS Services to 3.8.0 and enable Draft Messages

.github/dependabot.yml
Keep also the actions up-to-date following this approach: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
=> Keep also the actions up-to-date with dependabot

app/fiori.html
This version properly shows the field label in the error message popups, which is a long awaited feature :)
=> Use UI5 1.136.0

app/addresses/webapp/index.html, app/admin/webapp/index.html, app/browse-genres/webapp/index.html, app/browse/webapp/index.html, app/genres/webapp/index.html, app/notes/webapp/index.html, app/orders/webapp/index.html, app/reviews/webapp/index.html
Apps via direct link use different UI theme. This changes it to the `sap_horizon`.
=> Use `sap_horizon` everywhere

db/package-lock.json, db/package.json
Single Tenant build is broken due to upgrade to hdb ^2
=> Revert to hdb ^0

srv/src/main/resources/META-INF/native-image/resource-config.json
- Includes indices-h2.sql to Native Image
- messages.properties are added by Spring Boot automatically meanwhile
=> Fix Native Image resources
