srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java, srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java, srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java
the classes and constructors of spring beans don't
need to be public but can be package private. by this
manual construction and thereby circumventing dependency
injection is prevented. Unit tests need to reside in the same
package, though. But this is considered best practice anyhow.
=> make spring beans and their constructors package private

app/browse/fiori-service.cds, srv/admin-service.cds
The CDS VS Code Plugin now brings an annotation modeler and validator.
This change fixes some warnings and errors that it reported:
- @Capabilities.Insertable: false is not correct according to the OData Vocabularies
- The UI.HeaderInfo annotation was missing some mandatory fields
=> Fix warnings and errors from annotation modeler

mtx-sidecar/server.js
This unnecessary configuration can lead to problems with large request bodies.
=> Fix issue with large request bodies in mtx-sidecar

srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java
During a draft GC all drafts older than a specific time are deleted.
It is therefore not possible to recalculate elements for a specific draft and no draft ID can be obtained from the CQN.
We just skip our custom before handler in that case, which is anyway mainly useful in UI scenarios.
=> Make handler work with draft GC

srv/pom.xml
According the `cds build --help` output, the argument --clean is deprecated:
```
-c | --clean deprecated
Incremental builds are not supported.
Build output folders are always cleaned before build.
```
=> Remove deprecated cds build command from pom.xml

app/orders/fiori-service.cds
TargetProperties need to be passed as String values.
TargetEntities need to be used instead of using paths in TargetProperties.
=> Fix syntax of side-effects

db/package.json, mta-multi-tenant.yaml, mta-single-tenant.yaml, mtx-sidecar/package.json
Previously the build of the mtx-sidecar and db module required a
globally installed cds-dk, which is not fulfilled for pipeline builds or
staging on CF.
=> Fix cds build on cf and non dev environment

srv/src/main/java/my/bookshop/handlers/DestinationConfiguration.java, srv/src/main/resources/application.yaml
Reading the API Key is explicitly implemented in this sample application.
Adding that configuration to the destination configuration of a Remote Service creates the impression that this is natively supported by CAP.
This is however not the case. It also promotes the bad behaviour of extending CAPs configuration schemas with custom properties.
=> Don't mix destination configuration with SAP API Business Hub API Key

db/reviews.cds
Annotation to assert enums is called `@assert.range`, see also https://cap.cloud.sap/docs/guides/generic#assertrange-check-constraints
=> Fix annotation name

srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java
(please don't mind the incorrect branch name, it should rather be read-books-handler-robustness)
- we cannot rely on always having the id property of books here
- a request on books(ID=...)/title for example would run into an NPE
=> Improved robustness of setIsReviewable

.cdsrc.json, README.md, srv/pom.xml, srv/src/main/java/my/bookshop/handlers/BookRatingInitialization.java, srv/src/main/resources/application.yaml
To be improved in the future in `cds-services`:
- Auto-detection of H2 as embedded database
- Ability to disable detection of datasources from environment (e.g. `default-env.json`) -> previously covered by explicit `spring.datasource.url` configuration
=> Use H2 as in-memory database

pom.xml, srv/pom.xml
- Disabling forks also disables the Spring Developer Tools in the application
- see: https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-run-parameters-details-fork
=> Allow forking a subprocess to support Spring Boot Developer Tools

pom.xml
Avoid, managing non Cloud SDK dependencies (e.g. XSUAA)
=> Use Cloud SDK Modules BOM

README.md, mta-multi-tenant.yaml, mta-single-tenant.yaml
- Shorter app and hostnames to avoid errors with routes over 63 characters
- Make singletenant and multitenant deployable in the same space
- Add link to tutorial explaining how to create SAP HANA Cloud instance
=> Avoid Pitfalls in MTA deployment

db/books.cds, db/orders.cds, db/reviews.cds, pom.xml
latest version 5.2.0 of cds-lsp complains about unknown artefacts in cds model in Eclipse, e.g in reviews.cds
```
Description	Resource	Path	Location	Type
Artifact “my.bookshop.Books” has no element “reviews.book”	books.cds	/bookshop-parent/db	line 22	Language Servers
Artifact “my.bookshop.Reviews” has not been found	books.cds	/bookshop-parent/db	line 21	Language Servers
Artifact “my.bookshop.TechnicalBooleanFlag” has not been found	books.cds	/bookshop-parent/db	line 23	Language Servers
```
=> Added missing using statements

app/vue/app.js, pom.xml, srv/src/main/java/my/bookshop/handlers/ReviewsServiceHandler.java
Note:
When a review is added or updated in the Vue app (http://localhost:8080/vue/index.html), the method `afterAddReview(...)` in `ReviewsServiceHandler` is not triggered. I cannot figure out why.
=> Fix post path in Vue app; update dependencies in pom.xml

.gitignore, app/addresses/package.json, app/addresses/webapp/manifest.json, app/admin/package.json, app/admin/webapp/manifest.json, app/browse/package.json, app/browse/webapp/manifest.json, app/notes/package.json, app/notes/webapp/manifest.json, app/orders/package.json, app/orders/webapp/manifest.json, app/reviews/package.json, app/reviews/webapp/manifest.json
The changes are a precondition to deploy the UI5 applications in the `app` folder to the HTML5 repo and use them in the SAP BTP Launchpad Service. The changes for the `mta.yaml` deployment descriptor are not included.
* Added `package.json` required to run the UI5 build
* Added `applicationVersion` in `manifest.json` files to deploy to HTML5 repo
* Added `crossNavigation` in `manifest.json` files to add application as Launchpad tiles
=> Prepare applications for use with Launchpad Service and HTML5 repo

srv/src/main/resources/logback-spring.xml
Without the JsonEncoder the RequestLogger is no longer able to write request logs.
See also: https://github.com/SAP/cf-java-logging-support/issues/149
=> Disable RequestLogger in non-cloud profile

srv/cat-service.cds, srv/src/test/java/my/bookshop/CatalogServiceITest.java
Partially reverts https://github.com/SAP-samples/cloud-cap-samples-java/pull/156, now that we can reasonably opt-out of secure-by-default.
=> Make CatalogService public again

.cdsrc.json, mtx-sidecar/.cdsrc.json, pom.xml, srv/external/API_BUSINESS_PARTNER.csn, srv/pom.xml
- Use H2 v2 with new h2 dialect provided by CDS Compiler
- Use new name java instead of old java-cf for build tasks
- Update dependencies
=> Update CDS Services to 1.29.0

pom.xml, srv/external/API_BUSINESS_PARTNER.csn
Fixes H2 SQL issue, which required a small change to the original API_BUSINESS_PARTNER API
=> Update @sap/cds-dk to 6.3.2

db/package.json, mta-single-tenant.yaml
This PR removes the @sap/cds-dk installation from the build script in db/package.json. Now, the build script relies on a previous local installation of the cds-dk, e.g. done with a maven build. Or a globally installed cds-dk version is used.
The mbt build works fine, because first the srv module is built, then the db module.
=> remove cds-dk installation from build script of db

.github/workflows/maven.yml, README.md, mta-multi-tenant.yaml, mta-single-tenant.yaml, pom.xml, values.yaml
Switches sample to Java 17 as default. 
Additional space added to the Java backend to accommodate downloaded JRE. Sidecar is also grew bigger.
=> Switch to Java 17 as default

README.md
The `cds add helm:<feature>` commands don't exist any more. They are now merged with the standard `cds add <feature>` commands.
@BraunMatthias @mofterdinger @beckermarc
=> Fix `cds add helm` commands

.gitignore, pom.xml
Using the command line `mvn cds:watch` creates implicitly the file `src/main/resources/.reloadtrigger` which is not intended to be checked-in. Adding it to .gitignore solves this issue.
=> adding .reloadtrigger to .gitignore

pom.xml
maven-compiler-plugin ............................. 3.8.1 -> 3.10.1
maven-enforcer-plugin ........................... 3.0.0-M3 -> 3.2.1
maven-surefire-plugin ........................ 3.0.0-M5 -> 3.0.0-M9 
org.codehaus.mojo:flatten-maven-plugin ............. 1.2.5 -> 1.3.0
=> Version bump build plugins

mtx/sidecar/package.json, srv/src/main/java/my/bookshop/config/CustomFeatureToggleProvider.java, srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java, srv/src/main/resources/application.yaml, srv/src/test/java/my/bookshop/FeatureTogglesIT.java, srv/src/test/java/my/bookshop/handlers/CatalogServiceHandlerTest.java
- Reuse existing mock users instead of introducing new ones
- Avoid introducing another disocunt concept and reuse the existing one
=> Simplify Feature Toggles integration

mta-multi-tenant.yaml, mta-single-tenant.yaml
This is now mandatory on some landscapes, otherwise login fails.
It is also recommended by XSUAA here: https://help.sap.com/docs/btp/sap-business-technology-platform/security-considerations-for-sap-authorization-and-trust-management-service
=> Configure OAuth2 Redirect URI for XSUAA Login

srv/external.cds, srv/notes-mashup.cds
info messages are hidden by default. If enabled, there is a message about doc-comments not having any effect. `/** */` comments have special meaning in CDS: They contain documentation that is assigned to an artifact as a `doc` property in CSN.  To help users identify places where such a comment has no effect, an info message is provided.
This is just to be 100% message free.
=> fix: Fix compiler info messages to make the project message-free

fts/isbn/schema.cds
This PR demonstrates the annotation `@cds.collate`that can be used to disable language-depended ordering for String fields.
=> Apply @cds.collate : false to ISBN

srv/external.cds
The fact that `using { my.bookshop } from '../db/index';` created an implicit alias `bookshop` for the `my.bookshop` package, which is then even used to refer to `my.bookshop.Addresses` as `bookshop.Addresses` (although not even defined in `../db/index`) is not so easy to grasp.
The sample is now more explicit by referring to `my.bookshop.Addresses` and only importing `Orders` from `../db/index`
=> Make CDS sample more explicit

mta.yaml, package.json, pom.xml
We need to switch the Postgres-based sample from the SAP Java Buildpack to the CF one. SAP buildpack does not work with SSL support we delivered in the recent release.
=> Switch from sap_java_buildpack to java_buildpack

srv/pom.xml
with the prior path argument builds on windows could fail as the path separator was lost along the way. Now the path is quoted and treated as a whole. We tested this on Windows locally and this change fixed the failing build.
=> quote the path argument for the cds build command

srv/pom.xml, srv/src/main/resources/application.yaml, srv/src/main/resources/db/changelog/.gitignore, srv/src/main/resources/db/changelog/db.changelog-master.yaml, srv/src/test/java/my/bookshop/config/DatabaseConfiguration.java, srv/src/test/resources/application.yaml
With this PR the following changes are made:
- Also generate a delta DDL sql for current model changes against model v2.
- Also deploy current CDS development model as delta DDL sql to Postgres with Liquibase
- Ensure that the Postgres testcontainer instance is also restarted to avoid Liquibase issue due to modified changeset context for current dev DDL sql.
=> Generate current model changes into db/changelog/dev

.cdsrc.json, README.md
With CDS 7…
- The `target: "."` is automatically coming with profile `java`
- The `java` profile is auto-assigned if a `pom.xml` is found
→ We can simplify the config here even further
@beckermarc
=> Simplify `.cdsrc.json`

db/package.json, mtx/sidecar/package.json
@hdi-deployer in version 4.9.0 has an issue:
Error: Cannot find module 'core-util-is'
Version 4.8.2 is fine. Hence, we temporarily downgrade
=> downgrade @sap/hdi-deploy due to bug in 4.9.0

srv/src/main/resources/application.yaml
On SAP HANA use the [SQL Optimization Mode](https://cap.cloud.sap/docs/java/persistence-services#sql-optimization-mode) `hex`.
=> Use HEX mode on SAP HANA

pom.xml
Avoids GraalVM Native Image issues: https://github.com/spring-projects/spring-security/issues/14362
=> Downgrade Spring Boot to `3.2.0`

.github/workflows/maven.yml
- added postgres branch to build trigger
- updated actions to latest versions
=> Added postgres branch to build trigger

README.md
Closes #284 
Replaces the [deprecated](https://github.com/paketo-buildpacks/base-builder) `--builder paketobuildpacks/builder:base` with `--builder paketobuildpacks/builder-jammy-base`.
=> Avoid deprecated paketo builder

mta-multi-tenant.yaml, mta-single-tenant.yaml
Replaces the old buildpack with new one.
See https://community.sap.com/t5/technology-blogs-by-sap/sap-java-buildpack-2-jakarta-based-fresh-and-new/ba-p/13619580
=> Switch to Jakarta buildpack

.gitignore, mta.yaml, srv/src/main/resources/application.yaml
The library [Java CF Env](https://github.com/pivotal-cf/java-cfenv/tree/main/java-cfenv-boot) is added to the classpath by the java_buildpack on startup:
```
2024-05-17T14:13:47.36+0200 [STG/0] OUT -----> Downloading Java Cf Env 3.1.5 from https://java-buildpack.cloudfoundry.org/java-cfenv/java-cfenv-3.1.5.jar (found in cache)
```
cf_env detects the PostegreSQL binding and already sets the property `spring.datasource.url`:
```
{"msg":"Setting spring.datasource properties from bound service [bookshop-pg-db]","level":"INFO","written_ts":"1715940082155066735","logger":"io.pivotal.cfenv.spring.boot.CfDataSourceEnvironmentPostProcessor","written_at":"2024-05-17T10:01:22.155Z","thread":"main","type":"log"}
```
This disables the CDS datasource autoconfig and the PG datasource …
=> Suppress setting spring.datasource.url by cf_env

README.md
The log after running `mvn clean spring-boot:run` says:
```
INFO 36234 --- [  restartedMain] c.s.c.f.s.c.a.m.MockUsersSecurityConfig  : Added mock user {"name":"privileged","password":"","systemUser":false,"privileged":true,"internalUser":false,"roles":[],"attributes":{},"unrestricted":[],"additional":{},"valid":true}
INFO 36234 --- [  restartedMain] c.s.c.f.s.c.a.m.MockUsersSecurityConfig  : Added mock user {"name":"authenticated","password":"","systemUser":false,"privileged":false,"internalUser":false,"roles":[],"attributes":{},"unrestricted":[],"additional":{},"valid":true}
INFO 36234 --- [  restartedMain] c.s.c.f.s.c.a.m.MockUsersSecurityConfig  : Added mock user {"name":"admin","password":"admin","systemUser":false,"privileged":false,"internalUser":false,"roles":["admin"],"attributes" …
```
=> doc(README): Mention that there are default mock users for local dev

README.md
Many bash/shell snippets in the README use an environment variable `YOUR_CONTAINER_REGISTRY`, which is used as `$YOUR_CONTAINER_REGISTRY`.
However, that has the downside that if users copy & paste the snippet and accidentally press enter or use a shell that doesn't allow multi- line pasting (and executes it immediately), then the variable will be replaced by an empty string, because it wasn't set before.
It's good practice to make those snippets copy&paste-safe. We can achieve that by adding `:?` to the variable, which emits an error if the variable is unset or null.
See https://devhints.io/bash for a bash cheat sheet.
Example:
```sh
docker push ${YOUR_CONTAINER_REGISTRY:?}/bookshop-srv
```
On ZSH:
```
zsh: YOUR_CONTAINER_REGISTRY: parameter not set
```
On Bash:
```
bash: …
```
=> doc(README): Make shell snippet copy&paste safe

pom.xml
Solves issue with inconsistency of cds-dk and cds:
```
cds-dk [7.9.4], cds [7.9.2], compiler [4.9.4],
```
=> Version bump cds-dk and cds-services

package.json, pom.xml
`@cap-js/postgres` has an open dependency to cds-dk and cds:
"@sap/cds": ">=7.6", "@sap/cds-dk": ">=7.5"
This causes the usage of cds-dk 7 with cds 8, which is incompatible.
=> Add devDependency to @sap/cds@^7 to avoid using @sap/cds@8

integration-tests/pom.xml
Fixes warning:
```
[WARNING] The following dependencies could not be resolved at this point of the build but seem to be part of the reactor:
[WARNING] o my:bookshop:jar:1.0.0-SNAPSHOT (compile)
[WARNING] Try running the build up to the lifecycle phase "package"
```
=> Added test scope to dependency my:bookshop

db/package.json, integration-tests/pom.xml, mtx/sidecar/package.json, srv/pom.xml, srv/src/main/resources/application.yaml
This PR fixes test failures of the Bookshop ITests using CAP 3 and cds8.
* `authentication.normalize-provider-tenant: true` needs to be set in the `application.yaml` because current itest logic requires the provider tenant to be subscribed. The deployment shell script is setting this value to `false` using a `sed` command which requires this property to be available in the file
* `hdi-deploy` in version `5` does not bundle any hana db client, but comes with a post install script that checks that one client has been installed by an external party. As we don´t need db accesses in the ìnstall-dependencies` goal in `pom.xml`, we just set `--ignore-scripts`
=> Upgrade all components to cds8

.cdsrc.json, .gitignore, app/fiori.html, app/package-lock.json, app/package.json, db/package-lock.json, db/package.json, integration-tests/pom.xml, mtx/sidecar/package-lock.json, mtx/sidecar/package.json, package.json, pom.xml, srv/pom.xml
- Check in `package-lock.json` files to fix dependencies of Node-based apps.
- Use `moduleLookupDirectories` to find `@sap/cds-mtxs` modules from `mtx/sidecar`
- Use `@sap/cds-dk` with `npx --package` in cds-maven-plugin goals
- Delete `package.json` in root directory.
=> Fix dependency versions of npm packages

srv/review-service.cds
Reverts SAP-samples/cloud-cap-samples-java#328. 
Causes issues in native image build that need additional investigation.
=> Revert "Use expression annotations in @restrict"

.github/workflows/maven.yml
With [latest version](https://github.com/actions/setup-java/releases/tag/v4.3.0) the github action actions/setup-java supports installing sapmachine :-)
I think we should advertise our Java VM in our projects.
=> Use sapmachine for maven build

.github/workflows/maven.yml, README.md, integration-tests/pom.xml, pom.xml, srv/src/main/java/my/bookshop/handlers/AdminServiceAddressHandler.java, srv/src/main/java/my/bookshop/handlers/CatalogServiceHandler.java, srv/src/main/java/my/bookshop/handlers/NotesServiceHandler.java, srv/src/main/java/my/bookshop/handlers/SubscriptionHandler.java, srv/src/test/java/my/bookshop/AdminServiceAddressITestBase.java, srv/src/test/java/my/bookshop/CatalogServiceITest.java, srv/src/test/java/my/bookshop/CatalogServiceTest.java
- Use Java 21 to build sample application
- Use Openrewrite with recipe org.openrewrite.java.migrate.UpgradeToJava21 to demonstrate newer JDK APIs
- Update some outdated build plugins
- Bump enforced min. Maven to 3.6.3 -> required by cds-maven-plugin
=> Build with Java 21

app/orders/fiori-service.cds, app/orders/webapp/manifest.json
Cosmetic change: this change hides the `up__ID` from the change history view.
=> Hide up__ID in change tracking view

mta.yaml, srv/src/main/resources/application.yaml
Postgres 16 not available on BTP, using 15 instead.
Follow-up to https://github.com/SAP-samples/cloud-cap-samples-java/pull/391
=> Downgrade to Postgres 15

README.md, db/package-lock.json, db/package.json, srv/pom.xml
The PR contains some improvement suggestions. 
1. Adds the missing dev-dependency to @sap/cds-dk in the db module.
This fixes a problem that causes the build command to fail with `could not determine executable to run`
2. Adds an example route mapping to README.md
_Removed based on the communication._
~Fixes an issue in the Multi Tenancy example caused by a missing class.
Adds org.apache.commons:commons-collections4:4.4 as dependency. The dependency is required for com.sap.cds:cds-feature-mt:3.4.0 but never imported.
This is likely a bug in cds, but the import works around it.~
=> Improvement suggestions

srv/src/main/java/my/bookshop/handlers/HierarchyHandler.java
Custom handler for non-HANA DBs.
=> Demonstrate custom logic for Tree Tables

README.md, srv/src/test/java/my/bookshop/GenreHierarchyTest.java
- not testes with hybrid profile yet
- not everything is tested yet
=> Test: added tests for GenreHierarchy

db/data/sap.common-Currencies.csv, db/data/sap.common-Currencies.texts.csv
This change fixes local mtx setup for the application, so this does not happen after `cds subscribe t1 --to http://localhost:4005 -u yves:`
```
[error] - 500 > {
code: '500',
message: 'in cds.deploy(): near "from": syntax error in:\n' +
"INSERT INTO sap_common_Currencies_texts (CODE,LOCALE,NAME,DESCR) SELECT CASE WHEN OLD.locale IS NULL THEN value->>'$[0]' ELSE (CASE WHEN json_type(value,'$[0]') IS NULL THEN OLD.CODE ELSE value->>'$[0]' END) END as CODE,CASE WHEN OLD.locale IS NULL THEN value->>'$[1]' ELSE (CASE WHEN json_type(value,'$[1]') IS NULL THEN OLD.LOCALE ELSE value->>'$[1]' END) END as LOCALE,CASE WHEN OLD.locale IS NULL THEN value->>'$[2]' ELSE (CASE WHEN json_type(value,'$[2]') IS NULL THEN OLD.NAME ELSE value->>'$[2]' END) END as NAME,CASE WHEN OLD.locale IS NULL THEN …
```
=> Fix local mtx setup

srv/src/test/java/my/bookshop/GenreHierarchyTest.java
`assumeThat` seems to cause issues in Native Image-based test execution. Therefore using a plain old `if` 😄
=> Avoid assumeThat to fix Native Image tests

srv/src/main/java/my/bookshop/config/WebSecurityConfig.java
By default, CAP Java provides the open endpoints `actuator/health/liveness` and `actuator/health/readiness`. Both can be used by Cf or K8s for application health checks.
There is no need for a public `actuator/health` anymore.
See also in mta.yaml: https://github.com/SAP-samples/cloud-cap-samples-java/blob/228e05f940b4d22acc7d88c862fcb6e8c085ff40/mta-multi-tenant.yaml#L18
=> Remove open endpoint /actuator/health

app/admin/fiori-service.cds
=> Added missing label to UI annotation

app/_i18n/i18n.properties, app/_i18n/i18n_de.properties, pom.xml
With version 1.0.6 of the cds-feature-attachments, default UI texts are provided by the plugin itself.
=> Update cds-feature-attachments and re-use i18n

pom.xml, srv/pom.xml
In order to use the OSS variant of `cds-feature-event-hub` it needs to be possible to specify its version independently from the regular cds version
=> Allow to specify a dedicated version for cds-feature-event-hub

srv/admin-service.cds, srv/cat-service.cds
https://github.tools.sap/cap/cds-compiler/issues/13649
=> fix compiler error

srv/pom.xml, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java
Fixes https://github.com/SAP-samples/cloud-cap-samples-java/issues/452 
Workaround, that is currently required to restore the up__ID, which is no longer provided through the OData API due to containment.
=> Restore up__ID for covers

app/admin/fiori-service.cds, srv/admin-service.cds, srv/src/main/java/my/bookshop/handlers/AdminServiceHandler.java
Replaces https://github.com/SAP-samples/cloud-cap-samples-java/pull/456 by using a singleton, instead of adding a property to books.
=> Use singleton to show tree table only on HANA

mtx/sidecar/package-lock.json, mtx/sidecar/package.json, package-lock.json
`@cds/cds` does not yet support `express` in version 5. The previous dependabot upgrade broke the BTP integration tests with the following error. Switching back to version 4.
```
While resolving: @sap/cds@8.9.1
[2025-04-09T06:46:54.506Z] npm error Found: express@5.1.0
[2025-04-09T06:46:54.506Z] npm error node_modules/express
[2025-04-09T06:46:54.506Z] npm error   express@"^5" from the root project
[2025-04-09T06:46:54.506Z] npm error   peer express@">=4" from @sap/cds-fiori@1.4.1
[2025-04-09T06:46:54.506Z] npm error   node_modules/@sap/cds/node_modules/@sap/cds-fiori
[2025-04-09T06:46:54.506Z] npm error     @sap/cds-fiori@"^1" from @sap/cds@8.9.1
[2025-04-09T06:46:54.506Z] npm error
[2025-04-09T06:46:54.506Z] npm error Could not resolve dependency:
[2025-04-09T06:46:54.506Z] npm error …
```
=> Revert express upgrade

.github/dependabot.yml
Taken from this example: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#specifying-the-semantic-versioning-level-to-ignore
=> Ignore updates to express 5.x

app/admin/fiori-service.cds, app/browse/fiori-service.cds, app/common.cds
Use author_ID, as this brings proper text representation and also holds Value Helps.
Fixes https://github.com/SAP-samples/cloud-cap-samples-java/issues/474
=> Fix Manage Books UI

app/orders/webapp/manifest.json
Fiori always tries to path a collection values from which are used in the header. This should not happen for `book` as it is association.
This includes a workaround that makes these fields no longer editable.
=> Patch the issue on the object items detail page
